name: Boutique
main: com.danstoncube.plugin.drzoid.Boutique.Boutique
version: 2.0
website: http://www.danstoncube.com
author: DrZoid
description: Panneaux pour boutiques
commands:
  boutique:
    description: Permet la configuration des panneaux de vente.
    usage: |
           /<command> 
           /<command> -proprio   Pour changer le propriétaire d'un panneau.
           /<command> -coffre    Pour relier un coffre et un panneau.
           /<command> -vitrine   Pour relier un coffre et une vitrine.
  infoitem:
    description: Donne des informations sur l'objet tenu en main.
    usage: |
           /<command>
           Example: /<command>
